version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: order-mongodb-prod
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - order-network-prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ../../server
      dockerfile: Dockerfile.prod
    container_name: order-backend-prod
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/order?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - SUPER_ADMIN_USERNAME=${SUPER_ADMIN_USERNAME}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - order-network-prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ../../web
      dockerfile: Dockerfile.prod
    container_name: order-frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      - order-network-prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  order-network-prod:
    driver: bridge

volumes:
  mongodb_data:
